org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
jei_version=19.27.0.340
farmers_delight_version=1.21.1-1.3.0

mod_id=vintagedelight
mod_name=Vintage Delight
mod_license=MIT
mod_version=0.2.3
mod_group_id=net.ribs.vintagedelight
mod_authors=Ribs, duckgun13476, Polaris_Light, Pink_Cats, AraneaeDiscordia, Buttercup, Davey, community port contributors
mod_description=Adds fermentation, salt processing, crops, preserved foods, and Farmer's Delight integration.
